### PR TITLE
Dm 3175

### PR DESCRIPTION
**Pull request by JoshingYou1**
### JIRA issue link
https://agile6.atlassian.net/browse/DM-3175

## Description - what does this code do?
Changes the publication validation alert back to a modal

## Testing done - how did you test it/steps on how can another person can test it 
1. Log in as an admin.
2. Visit any practice editor page other than `Editors` and `Adoptions` for an unpublished practice.
3. Click on the "Save and publish" button.
4. Make sure the modal appears and contains a list of the missing fields required to publish a practice.
5. Click on the "Continue editing" button, click "Save as draft", and make sure the practice is saved correctly.
6. Click on the "Save and publish" button again.
7. Click somewhere inside of the modal (not on any of the buttons) and make sure the modal does not close.
8. Click somewhere outside of the modal and make sure the modal does close.
9. Click on the "Save and publish" button again.
10. Click on the "Save as draft and exit" and make sure you're redirected to the practice's show page.
11. Click on the browser's back button and click "Save as draft" again. Make sure the practice saves correctly and that you stay on the same practice page.

## Link to mock-ups/mock ups (image file if you have it) (if applicable)
https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Core-Designs---VA-DM?node-id=2188%3A11099

## Acceptance criteria
- Change the error message that appears on publish to be a modal
- After practice update then decide if we display this
- Instead of alert show modal

## Definition of done
- [X] Unit tests written (if applicable)
- [X] e2e/accessibility tests written (if applicable)
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [X] A link has been provided to the originating JIRA issue
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by emyl3 — CHANGES_REQUESTED** [review]
Let me know if you can repro this.
- Go to an unpublished practice with incomplete required fields for publishing.
- For example, go to the introduction section for a practice that doesn't have a tagline.
- Click "Save and publish"
- See in the modal that tagline isn't filled out.
- Go back and update the tagline and then click "Save and publish"
- The modal still shows that the tagline isn't filled out when it actually has been saved because when I refresh the page the updated tagline is still there

What I expected was the tagline not appearing on the list of fields that are required to be completed when seeing the publish modal show up after having filled it out and saving it.

Let me know if this makes sense 😄

**Review by bradjohnson92008 — CHANGES_REQUESTED** [review]
Great work Josh - this was a tough one.  Only issue I saw.. was that if you don't have an initiating facility (origin facility) and you update other parts of the Introduction form... and click  "Save as Draft"  this error will get raised and other data will not save.  Ping me if you want me to repro it for you.  
image

**Comment by JoshingYou1** [comment]
> Great work Josh - this was a tough one. Only issue I saw.. was that if you don't have an initiating facility (origin facility) and you update other parts of the Introduction form... and click "Save as Draft" this error will get raised and other data will not save. Ping me if you want me to repro it for you. image

Thanks Brad. I tested this out on the master branch and `feature/ie-rebrand` branch, and the behavior is the same. Maybe we need to create a bug story to address this issue, but the code in this PR did not manufacture it, and therefore would increase the scope of this particular story. Let me know if you have any questions.

**Review by bradjohnson92008 — APPROVED** [review]
Sounds good Josh - i.e., fixing the origin facility issue in a different story works for me.  Rest of the PR worked for me.

**Review by emyl3 — APPROVED** [review]
Worked for me! Great work on this!! 😸

**Review by bradjohnson92008 — APPROVED** [review]
Great job Josh.  I re-reviewed the PR and everything worked as intended.

**Review by emyl3 — APPROVED** [review]
Great work on this!! 😹

**Pull request merged**
