### PR TITLE
Dm 2600

### PR DESCRIPTION
**Pull request by JoshingYou1**
### JIRA issue link
https://agile6.atlassian.net/browse/DM-2600

## Description - what does this code do?
1. Sets a `user_type` in the session based on if the user is `NTLM` or not.
2. Adds `is_public` attr to practices and makes it configurable in the admin panel.

## Testing done - how did you test it/steps on how can another person can test it 
_**User type**_
1. In the `application_controller.rb` file, place a `debugger` after the `end` call on line `68`.
2. Visit `/`, make sure you hit the debugger, and then in the terminal write `session[:user_type]`. Make sure the value is `guest`.
3. Visit `/visns/1` and make sure you don't see the liaison section.

_**Public practices**_
1. Log in as an admin.
2. Visit `/admin/practices`.
3. On the right side of the table, click `Make public` for any practice, and make sure you see the confirmation message stating that the practice is now public.
4. Now click `Make private` for that same practice and make sure you see the confirmation message stating that the practice is now internal.

## Acceptance criteria
- Add field to user table
- Add field to Practice table
- Two statuses are VA user (NTLM) and Guest
- Ability to make practices public facing in Active Admin
- Deploy to Dev to test on GFE 
- Test

## Definition of done
- [X] Unit tests written (if applicable)
- [] e2e/accessibility tests written (if applicable)
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [X] A link has been provided to the originating JIRA issue
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by emyl3 — APPROVED** [review]
Looks good to me, Josh!

**Review by bradjohnson92008 — APPROVED** [review]
This looks to be working fine - great job as always Josh!.  The only question I have is if I'm signed in as an admin.. should the session[:user_type] still be set to "guest"?

**Review by emyl3 — APPROVED** [review]
looks good after the merge as well :D

**Comment by JoshingYou1** [comment]
> looks good after the merge as well :D

Thank you for re-reviewing this!!

**Pull request merged**
