### PR TITLE
DM-3028: Fixed focus issue for inputs on facilities search page

### PR DESCRIPTION
**Pull request by JoshingYou1**
### JIRA issue link
https://agile6.atlassian.net/browse/DM-3028

## Description - what does this code do?
Allows the user to keep focus on their previously selected input when using the facilities search functionality.

## Testing done - how did you test it/steps on how can another person can test it 
1. Visit `/facilities`
2. Play with the filters and make sure that after the results of your search have come back, that focus is brought back to whichever input you last interacted with.
3. **IMPORTANT:** I added the `disabled` attribute when the data is loading because randomly choosing inputs while it's loading had some weird side effects.
4. Try a bunch of different search to make sure everything is working properly.

## Acceptance criteria
- Only show the loading spinner for the table in the facilities search as opposed to the inputs and the table

## Definition of done
- [ ] Unit tests written (if applicable)
- [ ] e2e/accessibility tests written (if applicable)
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [X] A link has been provided to the originating JIRA issue
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by emyl3 — CHANGES_REQUESTED** [review]
Code-wise looked good to me! One thing I did notice though is that the combo box dropdown's chevron is no longer clickable so that it drops down a list of facilities even when the page is fully loaded. Good work, Josh!

**Comment by JoshingYou1** [comment]
> Code-wise looked good to me! One thing I did notice though is that the combo box dropdown's chevron is no longer clickable so that it drops down a list of facilities even when the page is fully loaded. Good work, Josh!

Good catch! I've fixed the issue. Thanks Elisa!

**Review by emyl3 — APPROVED** [review]
Looks good to me!

**Review by bradjohnson92008 — APPROVED** [review]
Works for me - great work Josh!

**Pull request merged**
