### PR TITLE
DM-3140: Add new header and footer for editor

### PR DESCRIPTION
**Pull request by emyl3**
### JIRA issue link
[DM-3140](https://agile6.atlassian.net/browse/DM-3140)

## Description - what does this code do?
This PR does the following:
- updates the header and footer for innovation editor pages
- removes the innovation editor side navigation
- makes the innovation editor pages 12 columns wide

## Testing done - how did you test it/steps on how can another person can test it 
Prereq
1. Have a user that can edit an innovation
2. Have a published innovation
3. Have an unpublished innovation

Unpublished innovation
1. Go to the show page of an unpublished innovation
2. Click the edit button
3. Ensure you are on the metrics page and see the new header and footer
4. Click on the header buttons (Note: "Editing guide" currently does not open the modal as it is not implemented)
5. The "Back" and "Continue" or "Save as continue" works as expected
6. Ensure the editor pages are all 12 columns
7. Ensure you see the "Save as draft" and "Save and publish" buttons as expected except for the editors and adoptions pages

Published innovation
1. Repeat steps 1-6 from above for published innovations
2. Ensure you see a "Save and update" button except for the editors and adoptions pages

## Link to mock-ups/mock ups (image file if you have it) (if applicable)
https://www.figma.com/file/dkvSpADVqwN5KKByF1TVIa/Design-system?node-id=1305%3A946
https://www.figma.com/file/ccwLbt94U9QGfnuFCwOXzY/Handoff?node-id=2173%3A4250

## Acceptance criteria
- [X] Remove all Side Nav code
- [X] Update Unit tests
- [X] Run tests to make sure we don’t break anything
- [X] Make all page 12 columns
- [X] Add new header Header (Edit, Metrics, “Save”)
- [X] Add new footer

## Definition of done
- [ ] Unit tests written (if applicable)
- [X] e2e/accessibility tests written (if applicable)
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [X] A link has been provided to the originating JIRA issue
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by JoshingYou1 — COMMENTED** [review]
Awesome job on this Elisa. Everything worked as intended. The only minor thing I noticed is that when I traveled from one editor page to the next, I was seeing the terms and conditions modal flicker on the screen. Maybe we could just add `display-none` to the modal itself and then when it arrives remove that class? This worked for me, but let me know what you think.

**terms_and_conditions.es6**
```
function loadTermsAndConditionsFn() {
     $(document).arrive("#dm-terms-and-conditions-modal", { existing: true }, (ele) => {
           $(ele).find('.usa-modal').removeClass("display-none");
            if (forceModal) {
                // display modal on page load if user is logged in and didn't accept terms
                $(ele).addClass("is-visible");
                $(ele).removeClass("is-hidden");
            }
      });
}
```

**_terms_and_conditions_modal.html.erb**
```
<div
  class="usa-modal display-none"
```

Repro:

**Review by bradjohnson92008 — COMMENTED** [review]
Worked for me Elisa... great work as always!

**Comment by emyl3** [comment]
> Awesome job on this Elisa. Everything worked as intended. The only minor thing I noticed is that when I traveled from one editor page to the next, I was seeing the terms and conditions modal flicker on the screen. Maybe we could just add `display-none` to the modal itself and then when it arrives remove that class? This worked for me, but let me know what you think.
> 
> **terms_and_conditions.es6**
> 
> ```
> function loadTermsAndConditionsFn() {
>      $(document).arrive("#dm-terms-and-conditions-modal", { existing: true }, (ele) => {
>            $(ele).find('.usa-modal').removeClass("display-none");
>             if (forceModal) {
>                 // display modal on page load if user is logged in and didn't accept terms
>                 $(ele).addClass("is-visible");
>                 $(ele).removeClass("is-hidden");
>             }
>       });
> }
> ```
> 
> **_terms_and_conditions_modal.html.erb**
> 
> ```
> <div
>   class="usa-modal display-none"
> ```
> 
> Repro: 

Thanks, Josh, for catching that! I had to do it slightly differently since that wasn't working for me locally. Let me know if waiting for the `body` works for you as well in terms of both preventing the flickering modal and also being able to see a terms and conditions modal :)

**Review by JoshingYou1 — APPROVED** [review]
I no longer see the terms modal flicker. Nice work! 😸

**Review by bradjohnson92008 — APPROVED** [review]
Works as intended for me... Great work Elisa

**Pull request merged**
