### PR TITLE
Dm 3113

### PR DESCRIPTION
**Pull request by JoshingYou1**
### JIRA issue link
https://agile6.atlassian.net/browse/DM-3113

## Description - what does this code do?
1. Changes the practice origin facilities selects to a single combobox and adds CRHs to the list of facilities.
2. Fixes a bug when trying to save practice partners.
3. General code cleanup.

## Testing done - how did you test it/steps on how can another person can test it 
# Practice Origin Facilities
1. Log in as an admin and visit the introduction page for a practice of your choosing.
2. Scroll down to the "Innovation origin" section and click on the "Facility" radio button.
3. Add as many facilities (`VaFacilities` or `ClinicalResourceHubs`) as you'd like, then save your progress. Make sure everything saves.
4. Now delete at least one entry, save your progress, and make sure it was removed from the list.
5. _**Edge Cases**_
    - Try to create a new facility that matches one that is already in the list, save your progress, and make sure it was not added to the list.
    - Make sure you have at least one facility created. Change the existing facility to a different one and then add a new entry and set it to the facility of the one you just changed, before you changed it (ex: The existing entry is Birmingham VA. Change it to Homer VA, and then add a new entry and set it to Birmingham VA). Save your progress and make sure the previously existing facility is changed and the new one is added to the list.
    - Make sure you have at least two facilities created. Delete the first existing facility, add a new entry and set the facility to the same one as the existing one you just deleted. Save your progress and make sure the first entry was not deleted and the new entry was not created.
    - Make sure you have at least one facility created. Change a facility to a different type (`VaFacility` to `ClinicalResourceHub`, or vice versa) and then create a new entry and set it to the facility name of the one you just changed, before you changed it (ex: The existing entry is Birmingham VA. Change it to VISN 1 Clinical Resource Hub, and then add a new entry and set it to Birmingham VA). Save your progress and make sure the original entry was updated and the new entry was added to the list.
    - Make sure you have at least two facilities created. Change an existing facility to match the value of another existing facility and save your progress. Make sure you get an error and that the practice does not save.
6. Try any other combinations you can think of, and make sure everything functions as it should.
7. Once you've finished testing on the editor side, visit the practice's show page and for the "ORIGIN" blurb, make sure the facilities are in alpha order and the link urls are correct.

# Practice Partners Bug Fix
1. Scroll down to practice partners.
2. Make sure you have at least one partner created. Change the existing partner to a different one and then add a new entry and set it to the partner name of the one you just changed, before you changed it (ex: The existing entry is Diffusion of Excellence. Change it to Office of Rural Health, and then add a new entry and set it to Diffusion of Excellence). Save your progress and make sure the previously existing partner is changed and the new one is added to the list.

## Screenshots, Gifs, Videos from application (if applicable)
# Basic Functionality

# Attempting to create a new facility even though it already exists

# Attempting to create blank entries

# Attempting to create duplicate new entries

# Changing an existing facility to a different one (`VaFacility` to `ClinicalResourceHub`) and then adding a new facility with the same name as the one that was changed

## Acceptance criteria
- Make Originating Location Facility Selector a combo box
- Remove state from Originating location facility selector
- Add CRHs to Facilities list (combo box) 
- Make sure you can see CRH as Originating location on innovation page

## Definition of done
- [X] Unit tests written (if applicable)
- [X] e2e/accessibility tests written (if applicable)
- [X] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [X] A link has been provided to the originating JIRA issue
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by bradjohnson92008 — COMMENTED** [review]
Great work Josh - everything worked for me accept the 1st edgeg case... I was able to save the same facility twice... (not 3 times though)..
image

**Review by bradjohnson92008 — APPROVED** [review]
We're good Josh - I tried it on 3 other practices locally and I couldn't repro either... it may just be that particular practice... bc I added a bunch of data manually to that practice to test other stuff.

**Comment by JoshingYou1** [comment]
> We're good Josh - I tried it on 3 other practices locally and I couldn't repro either... it may just be that particular practice... bc I added a bunch of data manually to that practice to test other stuff.

Okay, thank you Brad!!

**Review by bradjohnson92008 — APPROVED** [review]
last edge case there worked for me... could NOT change existing facility entry to another existing facility for that innovation.

**Pull request merged**
