### PR TITLE
Dm 3015

### PR DESCRIPTION
**Pull request by JoshingYou1**
### JIRA issue link
https://agile6.atlassian.net/browse/DM-3015

## Description - what does this code do?
Adds custom 404 page

## Testing done - how did you test it/steps on how can another person can test it 
1. In the `config/environments/development.rb` file, change `config.consider_all_requests_local = true` to `false`.
2. If your server was already running, restart it.
3. Visit a non-existent page (ex: '/hello-world') and make sure you see the custom 404 page.
4. Make sure the 'Visit homepage' link takes you to the homepage and the `Contact us' link takes you to the 'Contact us' portion of the About page.
5. From the 404 page, click on any random link or type in a new valid URL in the URL bar and visit a new page.
6. Click on the browser back button so you get taken back to the 404 page and make sure everything still functions as intended.

## Link to mock-ups/mock ups (image file if you have it) (if applicable)
https://www.figma.com/file/SI8tj1PhxPinElhQ3v8lGL/404-page?node-id=1%3A171

## Acceptance criteria
- Use Figma designed 404 page
- Implement

## Definition of done
- [X] Unit tests written (if applicable)
- [ ] e2e/accessibility tests written (if applicable)
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [X] A link has been provided to the originating JIRA issue
- [X] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by bradjohnson92008 — COMMENTED** [review]
Great job Josh - you turned this around quickly.   The 404 page looks and functions perfectly.  I tested quite a few paths...  only problem I saw was with /facilities/{show-page} if url can't be resolved here you'll get a 500 instead of redirected to 404 page.  i.e., /facilities/colorado-spring  Also the "consider_all_requests_local" value should be wet to true not false.

**Comment by JoshingYou1** [comment]
> Great job Josh - you turned this around quickly. The 404 page looks and functions perfectly. I tested quite a few paths... only problem I saw was with /facilities/{show-page} if url can't be resolved here you'll get a 500 instead of redirected to 404 page. i.e., /facilities/colorado-spring Also the "consider_all_requests_local" value should be wet to true not false.

Thanks Brad. I'll look into the facilities pages. I'm not sure I understand the second part. The `consider_all_requests_local` is set to true. You have to set it to false to see the 404 page locally

**Comment by bradjohnson92008** [comment]
Yeah - we're probably throwing an error upstream if there is no match for the facility... hence the 500.   Might want to run it by the team, but I'm fine with that... user is usually sent to show page from a link anyway.

**Review by emyl3 — CHANGES_REQUESTED** [review]
I think handling `navigation_helper` line 206 should address the issue brad found -- nice work josh!

**Review by emyl3 — APPROVED** [review]
Works for me! Nice job

**Review by bradjohnson92008 — APPROVED** [review]
Alls well!  Great work Josh!

**Pull request merged**
