### PR TITLE
Dm 3436

### PR DESCRIPTION
**Pull request by bradjohnson92008**
### JIRA issue link
https://agile6.atlassian.net/browse/DM-3436

## Description - what does this code do?
Updates va_facilities table with fresh facility data.  Data pulled from VAST on 6/17/2022

## Testing done - how did you test it/steps on how can another person can test it 

1. Check out the dm-3436 branch.  (updated va_facilities.json file is there).
2. From the console run the following rake task.  >rails va_facilities:create_or_update_va_facilities.  When the task is finished you should get a message ~ "All facilities have been updated or created"..
3. Do a select count(*) from va_facilities.  The total number of records should be 1,617 now.

## Screenshots, Gifs, Videos from application (if applicable)
N/A

## Link to mock-ups/mock ups (image file if you have it) (if applicable)
N/A

## Acceptance criteria

- Do VAST data pull of Facilities List 
- Update new columns (STA5A)
- Update JSON file of Facilities 
- Make sure CRHs are still intact 

## Definition of done
- [ ] Unit tests written (if applicable)
- [ ] e2e/accessibility tests written (if applicable)
- [ ] Events are logged appropriately
- [ ] Documentation has been updated, if applicable
- [ ] A link has been provided to the originating JIRA issue
- [ ] No sensitive information (i.e. PII/credentials/internal URLs/etc.) is captured in logging, hardcoded, or specs

### CODE REVIEW

**Review by JoshingYou1 — CHANGES_REQUESTED** [review]
Nice work on this Brad. In our `VaFacility` table (refer to: `20210217223013_create_vamcs.rb`), the majority of the columns have the data type of `string`, but this new json file has a lot of numbers, so we should either change them in the file, or add `.to_s` to the ones that are not strings in the rake file.

**Comment by bradjohnson92008** [comment]
Yeah I see point Josh...  I added the .to_s cast to the rake file... following properties... STA3N, Points_Of_Service, Street_Address_Zip_Code, Street_Address_Zip_Code_Extension, Mailing_Address_Zip_Code, and Mailing_Address_Zip_Code_Extension.  fyi - long and lat are decimal so leaving those as is.  I reran the script and it ran fine.. updated all 1,617 recs in my db.

**Comment by camillevilla** [comment]
7/6: added cast to string for numeric values

**Review by JoshingYou1 — APPROVED** [review]
LGTM!

**Pull request merged**
